### ISSUE TITLE
CSV file with wrong formatting confuses the system

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords-ui#54] opened 2016-10-03 14:14 UTC
I attempted to upload a CSV file, without having noticed that it wasn't in the right format to be processed as a database table (it was actually a file created by exporting an ORDS1 database: it contained the concatenated contents of several tables). I'd expect this to trigger some sort of error message saying that the file was unsuitable, but what actually happened was this:
- Clicking the 'Upload' button didn't appear to do anything (the same sort of thing that happens when trying to upload an SQL file, as per issue #52 )
- However, when I returned to the database page, I found that the file apparently _had_ uploaded - the original file name and size were listed, and the buttons had changed to 'View and edit database structure' etc. (this doesn't happen with SQL files)
- But on closer enquiry, the database was empty: no tables displaying in either the schema designer or the data viewer 
- I then found I was unable to delete the database version - clicking 'Delete' triggered the warning, but the metadata was still there after I'd told it to go ahead and delete.

The URL for the database page is https://trunkdb.com/app/#/project/1206/1413 - I'm happy to add other people as members of the project if that's useful.

I have since tried uploading this file again, and succeeded in replicating the first three points listed above, but not the fourth (i.e. I could delete the database version as normal).

**Comment by scottbw** [comment] 2017-05-23 09:11
I retried this and can't replicate it now - the uploader now gives an error message and stops the upload. I've tried it using:

- a PDF file
- a text file with .csv extension containing random stuff
- Excel sheet
- a text file with .csv extension containing malformed data a bit like Meriel's file (two tables with different columns in one file)

The text files generate a 500 error which I wasn't expecting, although the user message is sensible, so I'll investigate that further.

**Comment by scottbw** [comment] 2017-05-23 09:19
OK, I can see the logic behind it being a 500 as we don't know necessarily whether the problem is the file or a limitation of conversion, but in any case the main thing is that the user is informed correctly that the file uploaded but wasn't suitable for converting into a database. Closing.

**Closed as completed by scottbw** 2017-05-23 09:19 UTC
Labels: bug, High Priority, Projects and Databases Manager, Import/Export
