### ISSUE TITLE
Adding new relationships in schema designer freezes the system

### ISSUE THREAD

**Issue by MerielP** [ox-it/ords-ui#41] opened 2016-09-28 16:50 UTC
Adding a relationship between two tables in the schema designer makes the whole screen go grey. Nothing then seems to happen: the only way out I've found is to hit the Back button, which takes one back to the database page (hence losing any unsaved changes).

**Comment by scottbw** [comment] 2016-10-03 11:47
This was caused by a typo in the constraint URL - fixed in dev

**Closed as completed by scottbw** 2016-10-03 11:47 UTC
Labels: bug, Critical Priority, Schema Designer
